server:
  port: 8080

spring.jmx:
   enabled: false

spring.datasource.mysql:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crypto?autoReconnect=true&useSSL=false
    username: root
    password: root